import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { SignInButton, useUser } from "@clerk/nextjs";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

// import Link from "next/link";
import { api, type RouterOutputs } from "~/utils/api";

dayjs.extend(relativeTime);

//* =============================================
//*             CREATE POST WIZARD              =
//*==============================================
function CreatePostWizard() {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className="flex w-full gap-x-3">
      <Image
        src={user.profileImageUrl}
        alt={`${user.username || "User"}'s profile image`}
        className="h-14 w-14 rounded-full"
        width={56}
        height={56}
      />
      <input
        type="text"
        placeholder="Type some emojis"
        className="grow bg-transparent outline-none"
      />
    </div>
  );
}

//* =============================================
//*             POST WITH USER                  =
//*==============================================
type PostViewProps = RouterOutputs["posts"]["getAll"][number];

export function PostView({ author, post }: PostViewProps) {
  return (
    <div
      key={post.id}
      className="flex w-full gap-x-3 border-b border-slate-400 p-4"
    >
      <Image
        src={author.profileImageUrl}
        alt={`${author.username}'s profile image`}
        className="h-14 w-14 rounded-full"
        width={56}
        height={56}
      />
      <div className="flex flex-col">
        <p className="text-slate-300">
          <span>@{author.username}</span> <span>·</span>{" "}
          <span>{dayjs(post.createdAt).fromNow()}</span>
        </p>
        <span>{post.content}</span>
      </div>
    </div>
  );
}

//* =============================================
//*                 HOME PAGE                   =
//*==============================================
const Home: NextPage = () => {
  const { isSignedIn } = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-x-slate-400 md:max-w-2xl">
          <div className="flex border-b border-b-slate-400 p-4">
            {!isSignedIn ? (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            ) : (
              <CreatePostWizard />
            )}
          </div>
          <div className="flex flex-col">
            {data.map(({ post, author }) => (
              <PostView key={post.id} post={post} author={author} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
